/*
 * Copyright (c) 2008, Health XCEL Inc.. All Rights Reserved.
 */

package com.hxcel.globalhealth.domain.phr.model.enums;

public enum AllergyTypeCd {
    ANTI_ARRYTHMIA,
    ANTITOXIN,
    ASPIRIN,
    CODEINE,
    MORPHINE,
    MYCINS,
    NICKEL,
    DRUG_OTHER,
    OTHER_ANTIBIOTICS,
    PENICILLIN,
    SULFA_DRUGS,
    TETANUS,
    CORN,
    EGGS,
    FISH,
    MILK,
    FOOD_OTHER,
    PEANUTS,
    SHELLFISH,
    SOY,
    WHEAT,
    ANIMAL_DANDER,
    COCKROACH_DROPPINGS,
    COSMETICS,
    DUST_MITES,
    DYES,
    GRASSES,
    HAY_FEVER_POLLEN,
    INDUSTRIAL_CHEMICALS,
    INSECT_BITES_AND_STINGS,
    LATEX,
    LOCAL_ANESTHETICS,
    MOLD_SPORES,
    MOLDS,
    ENVIRONMENT_OTHER,
    PERFUMES_AND_FRAGRANCES,
    POISON_IVY,
    POISON_OAK,
    POISON_SUMAC,
    SERUMS,
    TREE_NUTS,
    TREES,
    WEEDS
}
