/*
 * Copyright (c) 2008, Health XCEL Inc.. All Rights Reserved.
 */

package com.hxcel.globalhealth.domain.phr.model.enums;

public enum ReligionCd {
    AFRICAN_TRADITIONAL_AND_DIASPORIC,
    BAHAI,
    BUDDHISM,
    CAO_DAI,
    CHINESE_TRADITIONAL_RELIGION,
    CHRISTIANITY,
    CONFUCIANISM,
    HINDUISM,
    ISLAM,
    JAINISM,
    JUCHE,
    JUDAISM,
    RASTAFARIANISM,
    SCIENTOLOGY,
    SECULAR_NONRELIGIOUS_AGNOSTIC_ATHEIST,
    SHAMANIST,
    SHINTO,
    SIKHISM,
    SPIRITISM,
    TAOSIM,
    TENRIKYO,
    TRIBAL_ANIMISM,
    WICCA,
    ZOROASTRIANISM,
    NEO_PAGANISM,
    PRIMAL_INDIGENOUS,
    UNITARIAN_UNIVERSALISM
}
